## NumPy

NumPy is a Python library, which adds support for large, multi-dimensional arrays and matrices, along with a large collection of optimized, high-level mathematical functions to operate on these arrays.

In [9]:
#!pip install numpy

In [3]:
import numpy as np

# 1. Create

In [6]:
data = np.random.rand(4,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [7]:
data

array([[[0.0343701 , 0.86034004, 0.07999108, 0.82240181],
        [0.29776535, 0.81717995, 0.93896298, 0.11221378],
        [0.60572209, 0.86592721, 0.08741118, 0.71748356]],

       [[0.73571374, 0.55596545, 0.28399991, 0.47949358],
        [0.04054956, 0.21759765, 0.90094697, 0.71052582],
        [0.64245682, 0.68401859, 0.5956421 , 0.1179955 ]],

       [[0.75490587, 0.95620087, 0.46067131, 0.38588869],
        [0.77300067, 0.95845911, 0.74134385, 0.67923916],
        [0.33904171, 0.22563092, 0.10580241, 0.53168759]],

       [[0.63801522, 0.83093959, 0.36637583, 0.38822595],
        [0.34770621, 0.08739465, 0.31090299, 0.45822502],
        [0.18041054, 0.42036101, 0.7686216 , 0.97902922]]])

In [8]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [12]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [10]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [22]:
type(arr)

numpy.ndarray

In [11]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

# 2. Read

In [13]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [14]:
types

dtype('float64')

In [15]:
# Slicing
arr = data[0] # First instance of data
reverse = data[-1]
singleval = data[0][0][0]

In [19]:
arr = data[0] # First instance of data
arr

array([[0.0343701 , 0.86034004, 0.07999108, 0.82240181],
       [0.29776535, 0.81717995, 0.93896298, 0.11221378],
       [0.60572209, 0.86592721, 0.08741118, 0.71748356]])

In [20]:
slicer = data[0][0:2] # First two of the following
slicer

array([[0.0343701 , 0.86034004, 0.07999108, 0.82240181],
       [0.29776535, 0.81717995, 0.93896298, 0.11221378]])

In [21]:
slicer2 = data[0]
slicer2

array([[0.0343701 , 0.86034004, 0.07999108, 0.82240181],
       [0.29776535, 0.81717995, 0.93896298, 0.11221378],
       [0.60572209, 0.86592721, 0.08741118, 0.71748356]])

In [16]:
singleval

0.03437010141289021

In [17]:
data

array([[[0.0343701 , 0.86034004, 0.07999108, 0.82240181],
        [0.29776535, 0.81717995, 0.93896298, 0.11221378],
        [0.60572209, 0.86592721, 0.08741118, 0.71748356]],

       [[0.73571374, 0.55596545, 0.28399991, 0.47949358],
        [0.04054956, 0.21759765, 0.90094697, 0.71052582],
        [0.64245682, 0.68401859, 0.5956421 , 0.1179955 ]],

       [[0.75490587, 0.95620087, 0.46067131, 0.38588869],
        [0.77300067, 0.95845911, 0.74134385, 0.67923916],
        [0.33904171, 0.22563092, 0.10580241, 0.53168759]],

       [[0.63801522, 0.83093959, 0.36637583, 0.38822595],
        [0.34770621, 0.08739465, 0.31090299, 0.45822502],
        [0.18041054, 0.42036101, 0.7686216 , 0.97902922]]])

# 3. Update

In [22]:
list1 = np.random.rand(10) 
list2 = np.random.rand(10) 

In [23]:
list2

array([0.48024619, 0.09120654, 0.01016138, 0.51767638, 0.15661307,
       0.59676387, 0.21476478, 0.22525463, 0.55076408, 0.27300417])

In [24]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [25]:
dot

1.5781581616646576

In [26]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [27]:
maxs

0.9880635880050685

In [28]:
data

array([[[0.0343701 , 0.86034004, 0.07999108, 0.82240181],
        [0.29776535, 0.81717995, 0.93896298, 0.11221378],
        [0.60572209, 0.86592721, 0.08741118, 0.71748356]],

       [[0.73571374, 0.55596545, 0.28399991, 0.47949358],
        [0.04054956, 0.21759765, 0.90094697, 0.71052582],
        [0.64245682, 0.68401859, 0.5956421 , 0.1179955 ]],

       [[0.75490587, 0.95620087, 0.46067131, 0.38588869],
        [0.77300067, 0.95845911, 0.74134385, 0.67923916],
        [0.33904171, 0.22563092, 0.10580241, 0.53168759]],

       [[0.63801522, 0.83093959, 0.36637583, 0.38822595],
        [0.34770621, 0.08739465, 0.31090299, 0.45822502],
        [0.18041054, 0.42036101, 0.7686216 , 0.97902922]]])

In [29]:
data[0][0][0] = 700

In [30]:
data

array([[[7.00000000e+02, 8.60340041e-01, 7.99910799e-02, 8.22401805e-01],
        [2.97765348e-01, 8.17179948e-01, 9.38962977e-01, 1.12213778e-01],
        [6.05722095e-01, 8.65927214e-01, 8.74111831e-02, 7.17483559e-01]],

       [[7.35713745e-01, 5.55965450e-01, 2.83999909e-01, 4.79493580e-01],
        [4.05495565e-02, 2.17597646e-01, 9.00946972e-01, 7.10525824e-01],
        [6.42456819e-01, 6.84018592e-01, 5.95642101e-01, 1.17995495e-01]],

       [[7.54905873e-01, 9.56200872e-01, 4.60671314e-01, 3.85888686e-01],
        [7.73000666e-01, 9.58459110e-01, 7.41343854e-01, 6.79239162e-01],
        [3.39041708e-01, 2.25630917e-01, 1.05802411e-01, 5.31687585e-01]],

       [[6.38015222e-01, 8.30939592e-01, 3.66375827e-01, 3.88225952e-01],
        [3.47706214e-01, 8.73946477e-02, 3.10902995e-01, 4.58225016e-01],
        [1.80410538e-01, 4.20361010e-01, 7.68621601e-01, 9.79029222e-01]]])

In [31]:
data.sort()
data

array([[[7.99910799e-02, 8.22401805e-01, 8.60340041e-01, 7.00000000e+02],
        [1.12213778e-01, 2.97765348e-01, 8.17179948e-01, 9.38962977e-01],
        [8.74111831e-02, 6.05722095e-01, 7.17483559e-01, 8.65927214e-01]],

       [[2.83999909e-01, 4.79493580e-01, 5.55965450e-01, 7.35713745e-01],
        [4.05495565e-02, 2.17597646e-01, 7.10525824e-01, 9.00946972e-01],
        [1.17995495e-01, 5.95642101e-01, 6.42456819e-01, 6.84018592e-01]],

       [[3.85888686e-01, 4.60671314e-01, 7.54905873e-01, 9.56200872e-01],
        [6.79239162e-01, 7.41343854e-01, 7.73000666e-01, 9.58459110e-01],
        [1.05802411e-01, 2.25630917e-01, 3.39041708e-01, 5.31687585e-01]],

       [[3.66375827e-01, 3.88225952e-01, 6.38015222e-01, 8.30939592e-01],
        [8.73946477e-02, 3.10902995e-01, 3.47706214e-01, 4.58225016e-01],
        [1.80410538e-01, 4.20361010e-01, 7.68621601e-01, 9.79029222e-01]]])

In [32]:
print(data.shape)

(4, 3, 4)


In [33]:
data = data.reshape((2,2,-1)) # Negative 1, if we do not care about the last value and let numpy decide
data.shape

(2, 2, 12)

In [34]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [35]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Delete

In [36]:
data

array([[[7.99910799e-02, 8.22401805e-01, 8.60340041e-01, 7.00000000e+02,
         1.12213778e-01, 2.97765348e-01, 8.17179948e-01, 9.38962977e-01,
         8.74111831e-02, 6.05722095e-01, 7.17483559e-01, 8.65927214e-01],
        [2.83999909e-01, 4.79493580e-01, 5.55965450e-01, 7.35713745e-01,
         4.05495565e-02, 2.17597646e-01, 7.10525824e-01, 9.00946972e-01,
         1.17995495e-01, 5.95642101e-01, 6.42456819e-01, 6.84018592e-01]],

       [[3.85888686e-01, 4.60671314e-01, 7.54905873e-01, 9.56200872e-01,
         6.79239162e-01, 7.41343854e-01, 7.73000666e-01, 9.58459110e-01,
         1.05802411e-01, 2.25630917e-01, 3.39041708e-01, 5.31687585e-01],
        [3.66375827e-01, 3.88225952e-01, 6.38015222e-01, 8.30939592e-01,
         8.73946477e-02, 3.10902995e-01, 3.47706214e-01, 4.58225016e-01,
         1.80410538e-01, 4.20361010e-01, 7.68621601e-01, 9.79029222e-01]]])

In [37]:
np.delete(data, 0, axis=1)

array([[[0.28399991, 0.47949358, 0.55596545, 0.73571374, 0.04054956,
         0.21759765, 0.71052582, 0.90094697, 0.1179955 , 0.5956421 ,
         0.64245682, 0.68401859]],

       [[0.36637583, 0.38822595, 0.63801522, 0.83093959, 0.08739465,
         0.31090299, 0.34770621, 0.45822502, 0.18041054, 0.42036101,
         0.7686216 , 0.97902922]]])

In [38]:
np.save("new array", data)

In [39]:
test = np.load("new array.npy")

In [40]:
test

array([[[7.99910799e-02, 8.22401805e-01, 8.60340041e-01, 7.00000000e+02,
         1.12213778e-01, 2.97765348e-01, 8.17179948e-01, 9.38962977e-01,
         8.74111831e-02, 6.05722095e-01, 7.17483559e-01, 8.65927214e-01],
        [2.83999909e-01, 4.79493580e-01, 5.55965450e-01, 7.35713745e-01,
         4.05495565e-02, 2.17597646e-01, 7.10525824e-01, 9.00946972e-01,
         1.17995495e-01, 5.95642101e-01, 6.42456819e-01, 6.84018592e-01]],

       [[3.85888686e-01, 4.60671314e-01, 7.54905873e-01, 9.56200872e-01,
         6.79239162e-01, 7.41343854e-01, 7.73000666e-01, 9.58459110e-01,
         1.05802411e-01, 2.25630917e-01, 3.39041708e-01, 5.31687585e-01],
        [3.66375827e-01, 3.88225952e-01, 6.38015222e-01, 8.30939592e-01,
         8.73946477e-02, 3.10902995e-01, 3.47706214e-01, 4.58225016e-01,
         1.80410538e-01, 4.20361010e-01, 7.68621601e-01, 9.79029222e-01]]])